<?php

namespace Levi9\BatteriesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BatteriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatteriesRepository extends EntityRepository
{
    /**
     * Returns statistics.
     *
     * @return array
     */
    public function getStatistics()
    {
        return $this->createQueryBuilder('b')
            ->select('SUM(b.count) AS stat_count, b.type')
            ->groupBy('b.type')
            ->getQuery()
            ->getResult()
        ;
    }

    /**
     * Delete all batteries.
     *
     * @return mixed
     */
    public function deleteAll()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->delete($this->getClassName())
            ->getQuery()
            ->execute();
    }
}
